### PR TITLE
First  Implementation of the Image Processor

### PR DESCRIPTION
**Pull request by TroyKomodo**
- [x] Add CI Tasks
- [x] Add the dump utils for webp and avif
- [x] Update README with build steps
- [x] Add unit tests

### CODE REVIEW

**Comment by TroyKomodo** [comment]
Some things i want to do is merge the image processor into this one, so that this repo contains go code aswell as c++ code, that might cause issues with how long the build takes but it might be a worthy trade off unless i use git cache perhaps thats better.

**Comment by AnatoleAM** [comment]
BASED if you read this

**Comment by AnatoleAM** [comment]
Okey if you read this

**Comment by AnatoleAM** [comment]
forsenE if you read this

**Pull request merged**
